# Generated by Django 4.1.2 on 2022-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('token_uri', models.CharField(max_length=1024)),
                ('client_id', models.CharField(max_length=1024)),
                ('client_secret', models.CharField(max_length=1024)),
                ('expiry', models.DateTimeField()),
            ],
        ),
    ]
